# Generated by Django 5.1.1 on 2024-09-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0004_accesslevel_user_manager_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='purchase_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
