# Generated by Django 5.1.1 on 2024-09-21 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0005_notification_purchase_type_user_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='model_email',
        ),
        migrations.AddField(
            model_name='notification',
            name='model',
            field=models.ForeignKey(default='ok', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='fls.model'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to=settings.AUTH_USER_MODEL),
        ),
    ]
