# Generated by Django 5.1.1 on 2024-09-23 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0006_remove_notification_model_email_notification_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='models_managed',
            field=models.ManyToManyField(related_name='users', to='fls.model'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='fls.organisation'),
        ),
    ]
