# Generated by Django 5.1.1 on 2024-09-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0007_remove_model_user_user_models_managed_and_more'),
        ('fls', '0008_auto_20240923_1030'),
    ]

    operations = [
    ]
