# Generated by Django 5.1.1 on 2024-09-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0009_merge_20240923_1038'),
        ('fls', '0010_auto_20240923_1044'),
    ]

    operations = [
    ]
