# Generated by Django 5.1.1 on 2024-09-23 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0011_merge_20240923_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='fls.organisation'),
        ),
    ]
