# Generated by Django 5.1.1 on 2024-09-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0013_auto_20240923_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhierarchy',
            name='role',
        ),
    ]
