# Generated by Django 5.1.1 on 2024-09-23 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0014_remove_userhierarchy_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhierarchy',
            name='organisation',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='orgid', to='fls.organisation'),
            preserve_default=False,
        ),
    ]
