# Generated by Django 5.1.1 on 2024-09-23 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0015_userhierarchy_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhierarchy',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchies', to='fls.organisation'),
        ),
    ]
