# Generated by Django 5.1.1 on 2024-09-23 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0016_alter_userhierarchy_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='managed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='managedby', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
