# Generated by Django 5.1.1 on 2024-09-23 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0017_model_managed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='fls.organisation'),
            preserve_default=False,
        ),
    ]
