# Generated by Django 5.1.1 on 2024-09-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0019_remove_user_models_managed_usermodelassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userhierarchy',
            unique_together={('user', 'supervisor')},
        ),
    ]
